git remote add girlsnrose     https://github.com/girlsnrose/spbetu_comparch_2022_1381.git     # Биктагирова Дарья    
git remote add Silence564     https://github.com/Silence564/spbetu_comparch_2022_1381.git     # Васильева Ольга      
git remote add vozmitelvlas   https://github.com/vozmitelvlas/spbetu_comparch_2022_1381.git   # Возмитель Влас	      
git remote add pddemchuk      https://github.com/pddemchuk/spbetu_comparch_2022_1381.git      # Демчук Полина        
git remote add denisova-ok    https://github.com/denisova-ok/spbetu_comparch_2022_1381.git    # Денисова Ольга       
git remote add snusoedochka   https://github.com/snusoedochka/spbetu_comparch_2022_1381.git   # Деркачева Дерья      
git remote add Dubars         https://github.com/Dubars/spbetu_comparch_2022_1381.git         # Дубовец Арсений      
git remote add maximdudko17   https://github.com/maximdudko17/spbetu_comparch_2022_1381.git   # Дудко Максим         
git remote add GeorIsay       https://github.com/GeorIsay/spbetu_comparch_2022_1381.git       # Исайкин Георгий      
git remote add donbase        https://github.com/donbase/spbetu_comparch_2022_1381.git        # Кагарманов Данис     
git remote add nikkupr98      https://github.com/nikkupr98/spbetu_comparch_2022_1381.git      # Куприянов Никита     
git remote add sashuliks      https://github.com/sashuliks/spbetu_comparch_2022_1381.git      # Куприянова Алексан   
git remote add LendorD        https://github.com/LendorD/spbetu_comparch_2022_1381.git        # Луценко Дмитрий      
git remote add LilChicha174   https://github.com/LilChicha174/spbetu_comparch_2022_1381.git   # Мамин Роман          
git remote add mantsevat      https://github.com/mantsevat/spbetu_comparch_2022_1381.git      # Манцева Татьяна      
git remote add Dalmatincoff   https://github.com/Dalmatincoff/spbetu_comparch_2022_1381.git   # Мелькумянц Данила    
git remote add PolinaNovak    https://github.com/PolinaNovak/spbetu_comparch_2022_1381.git    # Новак Полина         
git remote add Karina517      https://github.com/Karina517/spbetu_comparch_2022_1381.git      # Пекарчик Анна        
git remote add rymarmary      https://github.com/rymarmary/spbetu_comparch_2022_1381.git      # Рымарь Мария         
git remote add sinne0r        https://github.com/sinne0r/spbetu_comparch_2022_1381.git        # Сагидуллин Эрнест    
git remote add D1mitrii       https://github.com/D1mitrii/spbetu_comparch_2022_1381.git       # Смирнов Дмитрий      
git remote add ForthA         https://github.com/ForthA/spbetu_comparch_2022_1381.git         # Тарасов Константин   
git remote add mishatar       https://github.com/mishatar/spbetu_comparch_2022_1381.git       # Таргонский Михаил    
git remote add alisselisss    https://github.com/alisselisss/spbetu_comparch_2022_1381.git    # Тулегенова Алиса     
git remote add Astrokek       https://github.com/Astrokek/turkova.git                         # Туркова Дарья        
git remote add HyperChaos1337 https://github.com/HyperChaos1337/spbetu_comparch_2022_1381.git # Хомутинников Никита  
